  
name: smartify
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - opencv==4.0.1
  - numpy==1.19.4
  - pandas==1.1.3
  - pip==20.2.4
  - python==3.8.*
  - wheel=0.35.1
  - pip:
    - speechrecognition==3.8.1
    - youtube-dl==2020.11.12
    - python-vlc==3.0.11115
    - pafy==0.5.5
    - youtube-search-python==1.4.0
    - tinytag==1.5.0
    - paho-mqtt==1.3.1
    - matplotlib==3.2.2
    - tensorflow==2.3.1 #file too large, install if you want
